### ISSUE TITLE
Launcher rendering breaks from time to time

### ISSUE THREAD

**Issue by mr-pi12** [ATLauncher/ATLauncher#679] opened 2022-11-28 18:14 UTC
The launcher becomes glitchy wherever I move my mouse and while it's possible to click the buttons underneath the mess of broken UI, it becomes basically unusable without restarting the launcher.
![image](https://user-images.githubusercontent.com/76455683/204350531-414b046f-ef2e-4ebb-9d23-59ef46e38475.png)

**Comment by RyanTheAllmighty** [comment] 2022-11-28 22:27
Duplicate of #498 see that issue for workarounds which solve the issue

**Closed by RyanTheAllmighty** 2022-11-28 22:27 UTC
