### ISSUE TITLE
Instance and Server Mod management Feature Request

### ISSUE THREAD

**Issue by bkoee** [ATLauncher/ATLauncher#917] opened 2024-06-09 20:51 UTC
### The Problem

Inconsistent mod management.

### The Solution

It would be nice to have a search bar in the edit mods section of the instance manager. Having 120 mods installed is fairly difficult to find a troublesome mod to disable it. Some sort of mod version control would be nice so we can downgrade if an update broke a dependant mod (drop down next to the mod name). I would also like to see the same mod management functionality from the instance level be brought over to the server level.

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2024-06-09 22:17
Duplicate of #421 for servers and #556 for instances

**Closed by RyanTheAllmighty** 2024-06-09 22:17 UTC
Labels: enhancement, triage
