### ISSUE TITLE
Flatpak installation failure - Checksum mismatch

### ISSUE THREAD

**Issue by rventers** [ATLauncher/ATLauncher#707] opened 2023-01-15 21:09 UTC
**Describe the bug**
When installing ATLauncher via Flatpak CLI, the installation fails with a checksum mismatch error.

**To Reproduce**

1. Open terminal.
2. Type `flatpak install com.atlauncher.ATLauncher`

**Expected behavior**
ATLauncher installs successfully.

**Logs**
```
Error: While pulling app/com.atlauncher.ATLauncher/x86_64/stable from remote flathub: Checksum mismatch in static delta part; expected=7a55673892ac8b3f354c433affaa6ff957753ee9459e36e650faf9d10de3a71a actual=c22738448ba839fbca6452cbe758d93a5c1c2631701c4c558eda5f48702cc4c7
```

**Screenshots**
```
~ ❯ flatpak install com.atlauncher.ATLauncher
Looking for matches…

com.atlauncher.ATLauncher permissions:
    ipc    network    pulseaudio    x11   devices   file access [1]

    [1] xdg-download, xdg-run/app/com.discordapp.Discord:create


        ID                                  Branch          Op          Remote           Download
 1. [✗] com.atlauncher.ATLauncher           stable          i           flathub          1.0 kB / 82.1 MB

Error: While pulling app/com.atlauncher.ATLauncher/x86_64/stable from remote flathub: Checksum mismatch in static delta part; expected=7a55673892ac8b3f354c433affaa6ff957753ee9459e36e650faf9d10de3a71a actual=c22738448ba839fbca6452cbe758d93a5c1c2631701c4c558eda5f48702cc4c7
error: Failed to install com.atlauncher.ATLauncher: While pulling app/com.atlauncher.ATLauncher/x86_64/stable from remote flathub: Checksum mismatch in static delta part; expected=7a55673892ac8b3f354c433affaa6ff957753ee9459e36e650faf9d10de3a71a actual=c22738448ba839fbca6452cbe758d93a5c1c2631701c4c558eda5f48702cc4c7

~ ❯ 
```

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Fedora 37
- Java Version: N/A

**Additional context**
Ran `flatpak repair` but no issues were found and the above failure continued to occur.

**Comment by rventers** [comment] 2023-01-15 22:11
Possibility this is a larger Flathub issue and not one specific to the ATLauncher package. 

https://status.flathub.org/issues/2023-01-14-deltas/

**Comment by RyanTheAllmighty** [comment] 2023-01-15 22:21
Duplicate of #706

**Closed by RyanTheAllmighty** 2023-01-15 22:21 UTC
Labels: bug, duplicate
