### ISSUE TITLE
Do not delete config folder between modpack updates

### ISSUE THREAD

**Issue by GameBurrow** [ATLauncher/ATLauncher#850] opened 2023-11-17 09:45 UTC
### The Problem

Currently it seems that AT launcher deletes the config folder when client updates the modpack. This wipes all user custom client-side configs (even when modpacks use YOSBR, DefaultConfigs or any other similar mod), this is actually quite annoying.

### The Solution

Keep the configs folder between modpack updates

### Have you checked this issue doesn't already exist?

- [ ] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2023-11-17 09:51
Duplicate of https://github.com/ATLauncher/ATLauncher/issues/704

**Closed by RyanTheAllmighty** 2023-11-17 09:51 UTC
Labels: enhancement, triage
