### ISSUE TITLE
Blue screen during startup corrupted instance.json

### ISSUE THREAD

**Issue by Yentis** [ATLauncher/ATLauncher#951] opened 2024-08-26 16:11 UTC
### What happened?

1. Open ATLauncher
2. Start instance
3. Wait for initial loading screen to disappear
4. PC bluescreens
5. instance.json is corrupted and can no longer be loaded

I assume it bluescreened while it was being written to, so it may be useful to make a backup beforehand?

### Operating System

Windows

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2024-08-26 17:23
Duplicate of #878

**Closed by RyanTheAllmighty** 2024-08-26 17:23 UTC
Labels: bug, triage
