### ISSUE TITLE
UI Glitched/Bugged

### ISSUE THREAD

**Issue by its09avd** [ATLauncher/ATLauncher#783] opened 2023-07-15 09:31 UTC
### What happened?

It happens many times, the gui of the launcher starts glitching and wherever my mouse cursor is- only at that place the text/content is visible, the rest of the area gets all weird...
I am using a laptop with cpu ryzen 5600h and gpu amd rx5500m...

### Operating System

Windows

SCREENSHOTs -->
![Screenshot (7)](https://github.com/ATLauncher/ATLauncher/assets/81932625/15b6d9f6-128d-4041-bfef-ccb64d2c383b)

![Screenshot (8)](https://github.com/ATLauncher/ATLauncher/assets/81932625/9a618ab1-4cac-4d99-b119-86ef74c14fac)

**Comment by RyanTheAllmighty** [comment] 2023-07-15 11:12
Duplicate of #721

**Closed by RyanTheAllmighty** 2023-07-15 11:12 UTC
Labels: bug, triage
