### ISSUE TITLE
Cannot launch any instances on Linux ARM64

### ISSUE THREAD

**Issue by JMadgwick** [ATLauncher/ATLauncher#882] opened 2024-03-10 20:27 UTC
### What happened?

Using the JAR with Armbian Linux running on an Orange Pi 5 Plus with default Ubuntu built system Java 21.

1. Open ATLauncher
2. Install a vanilla pack (no mods)
3. Launch the instance
4. Minecraft fails to load (see log)

The problem is that the wrong LWJGL libraries are being installed. ARM64 should be used but X86 is getting installed by the launcher. I tried manually downloading/installing the correct JARs and renaming, but upon launching the game all modified JARs are automatically deleted and replaced.

After reading existing issues it seems this is intended to be supported and should be working.

ARM64 Linux is a niche platform, but it would be good if ATLauncher could support it, as unlike other launchers it is a JAR and not a binary blob which cannot even be run at all to begin with.

### Operating System

Linux

### Relevant log output

```shell
[10/03/2024 16:19:23 pm] Organising filesystem
[10/03/2024 16:19:23 pm] ATLauncher Version: 3.4.35.9 [1a4c0516cf5535166297e88e3239c78086db8589]
[10/03/2024 16:19:23 pm] App Arguments: []
[10/03/2024 16:19:23 pm] JVM Arguments: []
[10/03/2024 16:19:23 pm] Java Version: Java 21 (21.0.2)
[10/03/2024 16:19:23 pm] Java Path: /usr/lib/jvm/java-21-openjdk-arm64
[10/03/2024 16:19:23 pm] 64 Bit Java: true
[10/03/2024 16:19:23 pm] RAM Available: 15718MB
[10/03/2024 16:19:23 pm] Launcher Directory: **USERSDIR**
[10/03/2024 16:19:23 pm] Arm: 64
[10/03/2024 16:19:23 pm] GPU: unknown (unknown) unknown 0MB VRAM
[10/03/2024 16:19:23 pm] CPU: Orange Pi 5 Plus 8 cores/8 threads
[10/03/2024 16:19:23 pm] Operating System: Ubuntu (22.04.4 LTS (Jammy Jellyfish) build 5.10.160-legacy-rk35xx)
[10/03/2024 16:19:23 pm] Bitness: 64
[10/03/2024 16:19:23 pm] Uptime: 9052
[10/03/2024 16:19:23 pm] Manufacturer: GNU/Linux
[10/03/2024 16:19:23 pm] Showing splash screen and loading everything
[10/03/2024 16:19:23 pm] Checking for updated files!
[10/03/2024 16:19:24 pm] Launcher finished loading everything
[10/03/2024 16:19:24 pm] Launcher opening
[10/03/2024 16:19:24 pm] Made By Bob*
[10/03/2024 16:19:24 pm] *(Not Actually)
[10/03/2024 16:19:24 pm] Setting up Bottom Bar
[10/03/2024 16:19:24 pm] Finished Setting up Bottom Bar
[10/03/2024 16:19:24 pm] Setting up Tabs
[10/03/2024 16:19:25 pm] Finished Setting up Tabs
[10/03/2024 16:19:25 pm] Showing Launcher
[10/03/2024 16:19:35 pm] Preparing for launch!
[10/03/2024 16:19:35 pm] Launching pack Minecraft 24w10a (Vanilla) for Minecraft 24w10a
[10/03/2024 16:19:35 pm] Logging into Minecraft!
[10/03/2024 16:19:35 pm] Launching Minecraft with the following arguments (user related stuff has been removed): [/usr/lib/jvm/java-21-openjdk-arm64/bin/java, -Xmx4096M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dlog4j.configurationFile=USERSDIR/assets/log_configs/client-1.12.xml, -XX:+UnlockExperimentalVMOptions, -XX:+UseG1GC, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=32M, -Xss1M, -Djava.library.path=USERSDIR/temp/natives-ee6efa1e0f0b409282c169fde7fd0c6a, -Djna.tmpdir=USERSDIR/temp/natives-ee6efa1e0f0b409282c169fde7fd0c6a, -Dorg.lwjgl.system.SharedLibraryExtractPath=USERSDIR/temp/natives-ee6efa1e0f0b409282c169fde7fd0c6a, -Dio.netty.native.workdir=USERSDIR/temp/natives-ee6efa1e0f0b409282c169fde7fd0c6a, -Dminecraft.launcher.brand=ATLauncher, -Dminecraft.launcher.version=3.4.35.9, -cp, USERSDIR/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar:USERSDIR/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:USERSDIR/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:USERSDIR/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar:USERSDIR/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar:USERSDIR/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar:USERSDIR/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:USERSDIR/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar:USERSDIR/libraries/com/mojang/datafixerupper/6.0.12/datafixerupper-6.0.12.jar:USERSDIR/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar:USERSDIR/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:USERSDIR/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:USERSDIR/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar:USERSDIR/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar:USERSDIR/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:USERSDIR/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar:USERSDIR/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar:USERSDIR/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar:USERSDIR/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar:USERSDIR/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar:USERSDIR/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar:USERSDIR/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar:USERSDIR/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar:USERSDIR/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar:USERSDIR/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar:USERSDIR/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar:USERSDIR/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar:USERSDIR/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:USERSDIR/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:USERSDIR/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar:USERSDIR/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar:USERSDIR/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:USERSDIR/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar:USERSDIR/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:USERSDIR/libraries/org/lwjgl/lwjgl-freetype/3.3.2/lwjgl-freetype-3.3.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-freetype/3.3.2/lwjgl-freetype-3.3.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-linux.jar:USERSDIR/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:USERSDIR/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:USERSDIR/libraries/net/minecraft/client/24w10a/client-24w10a.jar, net.minecraft.client.main.Main, --username, REDACTED, --version, 24w10a, --gameDir, USERSDIR/instances/Minecraft24w10a, --assetsDir, USERSDIR/assets, --assetIndex, 14, --uuid, REDACTED, --accessToken, REDACTED, --userType, msa, --versionType, snapshot, --width=854, --height=480,]
[10/03/2024 16:19:42 pm] [Datafixer Bootstrap/INFO] 217 Datafixer optimizations took 366 milliseconds
[10/03/2024 16:19:43 pm] [LWJGL] Platform/architecture mismatch detected for module: org.lwjgl
[10/03/2024 16:19:43 pm] 	JVM platform:		Linux aarch64 21.0.2
[10/03/2024 16:19:43 pm] 		OpenJDK 64-Bit Server VM v21.0.2+13-Ubuntu-122.04.1 by Private Build
[10/03/2024 16:19:43 pm] 	Platform available on classpath:
[10/03/2024 16:19:43 pm] 		linux/x64
[10/03/2024 16:19:43 pm] [LWJGL] Failed to load a library. Possible solutions:
[10/03/2024 16:19:43 pm] 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
[10/03/2024 16:19:43 pm] 	b) Add the JAR that contains the shared library to the classpath.
[10/03/2024 16:19:43 pm] [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[10/03/2024 16:19:43 pm] [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at ab.a(SourceFile:66)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at fby.a(SourceFile:2599)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at fby.a(SourceFile:2574)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:233)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so [in thread "Render thread"]
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:174)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:64)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:52)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at evp.<clinit>(SourceFile:8)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at ewm.<init>(SourceFile:49)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at ewt.<init>(SourceFile:33)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:50)
[10/03/2024 16:19:43 pm] [Render thread/INFO] [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:220)
[10/03/2024 16:19:43 pm] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[10/03/2024 16:19:43 pm] Checking for updated files!
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2024-03-10 23:46
Duplicate of #576

**Closed by RyanTheAllmighty** 2024-03-10 23:46 UTC
Labels: bug, triage
