### ISSUE TITLE
extraarguments ignored, but compared for duplicates

### ISSUE THREAD

**Issue by Haggle1996** [ATLauncher/ATLauncher#234] opened 2015-12-22 06:48 UTC
It seems ATLauncher is ignoring arguments passed in the <extraarguments> line in my pack config.

Changing to <extraarguments>-XX:+UseG1GC --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker</extraarguments> results in the parameter not present in this line in the log:

[21/12/2015 23:11:27 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre1.8.0_65\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -Xms256M, -Xmx4096M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=FINEST, -Djava.library.path=**USERSDIR**\Instances\Revolution2\bin\natives, -cp

Adding -XX:+UseG1GC to the Java Parameters settings results in these lines:
[21/12/2015 23:12:55 PM] Duplicate argument -XX:+UseG1GC found and not added!
[21/12/2015 23:12:55 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre1.8.0_65\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -Xms256M, -Xmx4096M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=FINEST, -Djava.library.path=**USERSDIR**\Instances\Revolution2\bin\natives, -cp

Removing the argument from <extraarguments>, but leaving them in the global settings results in a correct line:
[21/12/2015 23:15:06 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre1.8.0_65\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -Xms256M, -Xmx4096M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=FINEST, -XX:+UseG1GC, -Djava.library.path=**USERSDIR**\Instances\Revolution2\bin\natives, -cp

**Comment by RyanTheAllmighty** [comment] 2015-12-24 06:19
Will look into this in the new year once I hopefully get back into working on the client

**Comment by WesCook** [comment] 2015-12-28 00:14
@Haggle1996, just wondering if you need -XX:+UseG1GC for Chromaticraft?  That's my current issue.  The [latest version](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/208) requires this in Java 8.

So as I understand, there's no current way to add an extra command parameter in ATL?  Will have to hold back Chromaticraft until then.  No rush - I'm just glad Reika toned down the notification alert.

**Comment by Haggle1996** [comment] 2015-12-28 00:36
Yes, it's for the ChromatiCraft support.

**Comment by RyanTheAllmighty** [comment] 2016-02-08 09:11
@Haggle1996 I'm having issues replicating this issue.

Can you provide a couple examples of what works and what doesn't work from your <pack></pack> section of your XML please.

**Comment by Haggle1996** [comment] 2016-02-08 16:56
This ```<extraarguments>-XX:+UseG1GC --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker</extraarguments>``` doesn't work. My players have to manually ad the -XX:+UseG1GC line to their java arguments.

**Comment by RyanTheAllmighty** [comment] 2016-02-08 19:30
That's odd as in my tests yesterday I had no issues with the same line.

Can you gather a few logs of the issue occurring to shed some insight please?

Also if you have a pack and version name to give me where it occurs so I can test with a live pack. If it's a dev version, username is the same as here.

**Comment by Haggle1996** [comment] 2016-02-08 21:36
Pack is 'Revolution 2' (not the original Revolution) on the launcher. You're added to the pack testers list. I have not tested this issue since back in December (and had removed the option in the interim since it interfered with the manually-supplied Java arguments). It's added to the dev version now. I will test it later this evening when I get home from work.

**Comment by RyanTheAllmighty** [comment] 2016-02-09 00:13
Okay I've installed the development option selecting the Recommended mods and I can't see the issue happening. The arguments are there and being put into the command running Minecraft. So maybe this issue isn't affecting newer versions of the code?

Can you download the latest dev version of the pack from [here](https://build.atlcdn.net/job/ATLauncher/lastSuccessfulBuild/) and see if the issue occurs for you on that build.

**Comment by Haggle1996** [comment] 2016-02-09 00:33
The G1GC option is present on the command line, however, ATLauncher doesn't recognize that the option is mutually exclusive with other garbage collector options (like UseConcMarkSweepGC), so it includes both. Java ignores the later argument.

**Comment by RyanTheAllmighty** [comment] 2016-02-11 14:24
Okay so the issue isn't the launcher, it's Java discarding duplicate 'like' options for the GC?

I'm not sure how this is something the launcher can handle. Please let me know what you see as the problem and the solution as I'm not sure I'm understanding it correctly.

From what I can see the `-XX:+UseG1GC` option is added in regardless of if it's in the XML or in the users java options or both.

**Comment by Haggle1996** [comment] 2016-02-11 14:44
What I think should change about the launcher is what happens when additional arguments (besides the tweakClass=cpw.mods.fml.common.launcher.FMLTweaker) is specified by the pack author. 

If there's anything in extraarguments, the launcher shouldn't provide any arguments (except maybe for RAM) and instead leave the entire set of arguments to the pack author. 

If the extraarguments line only contains the FMLTweaker class, it should follow the existing logic.

**Comment by dgelessus** [comment] 2016-02-11 18:00
That seems like a very risky assumption... just because a pack author specified custom extra arguments doesn't mean that the launcher's ones are unwanted. This change could break any modpack that previously used more than one extra argument and relied on the launcher's default arguments to work properly.

Also, am I missing something here, or could you simply disable the conflicting default option using `-XX:-UseConcMarkSweepGC`?

**Comment by Haggle1996** [comment] 2016-02-11 18:14
The problem is that Reika's mods require the G1GC option, which is mutually
exclusive with UseConcMarkSweepGC.

**Comment by WesCook** [comment] 2016-02-11 18:34
Sorry, but to clarify, does `-XX:-UseConcMarkSweepGC` enable or disable the GC?  Most Java args use a plus sign at the front I believe.  If this does indeed disable it, then this seems like a viable solution.

**Comment by RyanTheAllmighty** [comment] 2016-02-11 23:13
Yeah as @dgelessus mentions, it's a risky assumption to make and one that could ruin the game for people.

Some people rely on Java options to run packs consistently and just removing all their options because a pack specified custom arguments seems like a really bad call to make.

But as @WesCook mentions, can you not just disable the conflicting options? I'm not entirely sure how Java parses the options and deals with an enable and disable of the same argument.

I mean we could just detect if someone is using `-XX:+UseConcMarkSweepGC` and the pack has `-XX:+UseG1GC` and remove the `-XX:+UseConcMarkSweepGC` option, but I feel that doing so may lead to issues.

As a compromise if there is no other solution found, I can always add something like a `<removejavaoptions>UseConcMarkSweepGC,SomeOtherOptionMatchedByName</removejavaoptions>` which would simply remove all Java options matching those names for compatibility.

**Comment by Haggle1996** [comment] 2016-02-12 03:08
I'll play with it a bit more in the morning and see if I can get it to work appropriately; I'll report back here regardless.

**Comment by dgelessus** [comment] 2016-02-12 06:13
`-XX:+Whatever` enables the special option `Whatever` and `-XX:-Whatever` disables it (note the `+` and `-` before the name). It would make sense that one option overrides the other, and whichever one comes last takes priority (though I still need to test that).

**Comment by dgelessus** [comment] 2016-02-12 07:24
I think that's how it works:

```sh
$ java -XX:+UseConcMarkSweepGC -XX:+UseG1GC Test
Conflicting collector combinations in option list; please refer to the release notes for the combinations allowed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
$ java -XX:+UseConcMarkSweepGC -XX:-UseConcMarkSweepGC -XX:+UseG1GC Test
$ 
```

**Comment by RyanTheAllmighty** [comment] 2016-02-12 08:45
I mean I don't mind adding in blocks for individual packs for java options as I mentioned, but I think launcher wide restrictions/opinions on which java options override which other options is a bad idea, I may be wrong on this, and it should be a part of the pack development process given finer control.

**Comment by WesCook** [comment] 2016-02-12 09:13
I definitely agree that the launcher shouldn't be "opinionated" in that respect, unless absolutely necessary.  I just didn't realize multiple arguments were possible earlier.

So my suggestion would be first testing to see if @dgelessus's code above works in the launcher.  @Haggle1996, could you do so?  I've closed down my server so can't test it anymore.

If that works, then problem solved IMO.  If not, then a second-best option would be <removejavaoptions> as you described above Ryan.

**Comment by Haggle1996** [comment] 2016-02-12 17:52
@dgelessus variant works. A pack author would just need to explicitly remove all the conflicting options themselves AND ATLauncher needs to insure any options it provides automatically are added before any options added by modpack authors.

**Comment by dgelessus** [comment] 2016-02-12 18:16
The first shouldn't be an issue, as it's always safe to specify redundant options (e. g. `-XX:-UseG1GC` even though it's disabled by default already), so even if the launcher's options change at some point things shouldn't break because a default option was removed. It might be an issue though if new default options are added...

The second is already the case as far as I know, and that's the only thing that makes sense. The order should probably be "launcher, pack, user", that way the pack options have priority over the launcher defaults and the user can still add manual fixes in case the pack options do break on their machine.

**Comment by Haggle1996** [comment] 2016-02-12 18:20
Yes, if that is the case, then I vote to close this issue, as is.

**Comment by RyanTheAllmighty** [comment] 2016-02-13 08:08
Alright I'll check the order of the arguments and make adjustments and close the issue.

**Comment by RyanTheAllmighty** [comment] 2016-02-13 14:49
Alright seems the options were already in the right order, so closing this.

**Comment by pikkon38** [comment] 2016-02-25 05:48
I am still getting this issue. No args I put into <extraarguments> get read. I have even tried this:

<extraarguments>-XX:-CMSIncrementalMode -XX:+UseG1GC -XX:+UseConcMarkSweepGC -XX:-UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker</extraarguments>

with some of the guidance above, putting + then - for the ConcMarkSweepGC, and I still get a crash saying UseG1GC is required. I have done just about every combo of the above args, including just UseG1GC and the FMLTweaker arg.

**Comment by RyanTheAllmighty** [comment] 2016-02-25 07:16
Can you please provide the name of your pack, the name of a development version with the issue occurring and also add RyanTheAllmighty to the testers list and I can investigate this weekend.

**Comment by pikkon38** [comment] 2016-02-25 15:46
Sure thing.
Pack Name: BeachBlock Modsplosion
Dev Version: devModsplosion (search keywords in launcher are beach block)
You are now added to the testers

**Comment by pikkon38** [comment] 2016-03-03 21:19
Hey Ryan. Sorry, not trying make it seem like I keep bugging you about this, but I was wondering if you had a chance to look into this? It seems even when I put the args inside the ATLauncher java settings section on my client they fail to get recognized...

**Comment by RyanTheAllmighty** [comment] 2016-03-04 05:30
Not yet sorry.

I've setup some time this weekend to go through issues so will do it then.

**Comment by pikkon38** [comment] 2016-03-04 20:46
Okay no worries. Just curious :) This issue is really the only thing keep the pack from being submitted to publishing. If it turns out to be just an issue with that specific java arg, then I might just remove the mod from the pack, but Id rather try to leave it in :)

**Comment by RyanTheAllmighty** [comment] 2016-03-06 06:59
Alright so as a solution to this issue I've now made it so when you have -XX:- in your arguments and a user has the same -XX:+ in their arguments (including the defaults when the user has none specified) then it will negate it correctly and remove them both from being added when launching Minecraft which should solve this issue when released with 3.2.3.2

**Comment by pikkon38** [comment] 2016-03-06 07:04
Awesome! Thanks for looking into this and fixing it :) I appreciate it!

**Comment by RyanTheAllmighty** [comment] 2016-03-06 07:07
@pikkon38 @Haggle1996 if you can test with the version from https://build.atlcdn.net/job/ATLauncher/55/ to confirm it works or not, that would be excellent

**Comment by pikkon38** [comment] 2016-03-06 07:26
I'll give it a try first thing tomorrow morning as its 11:30pm here :)

**Comment by pikkon38** [comment] 2016-03-06 15:22
Hey Ryan, when trying to play an instance of a pack, I get a popup error saying Error:Could not create the Java virtual machine and that a fatal error occured and the program will exit. Basically I get this same issue: http://www.tomsguide.com/faq/id-1761312/fix-create-java-virtual-machine-issue.html

**Comment by pikkon38** [comment] 2016-03-06 15:23
Definitely sounds like a ram allocation issue from all the threads I've looked at, and I cannot add Xmx or Xms into the java args section in the launcher as the launcher slaps my wrist essentially and wont save.

**Comment by pikkon38** [comment] 2016-03-06 15:28
I even tried force putting the java args right in the instance json in the instance of my pack, and still no go

**Comment by dgelessus** [comment] 2016-03-06 15:37
If you need to change how much RAM the JVM should use, the launcher has built-in options for that. Use them, and don't try to add the arguments by hand, and especially don't follow the advice on that website you linked as that will override the launcher's RAM settings (although I think the launcher now forcefully ignores the `_JAVA_OPTIONS` envvar because so many people had bad options in it).

Also just in case you may want to do a full uninstall of Java and reinstall the latest 64-bit Java 8 from [here](https://java.com/en/download/manual.jsp).

**Comment by pikkon38** [comment] 2016-03-06 15:39
Yeah I tried in the launcher too. But I think I jumped the gun a bit. It is throwing a fit with my args in the log, saying The CMS collector (-XX:+UseConcMarkSweepGC) must be selected in order. Trying to trouble shoot it now. It seems like it doesnt like the Garbage collected turned off, even if I turned on the other one

**Comment by pikkon38** [comment] 2016-03-06 15:43
It appears adding -XX:+UseG1GC in the java args in the launcher fixes this issue. In my XML, I set -XX:+UseG1GC -XX:-UseConcMarkSweepGC. This disables the UseConcMarkSweepGC as expected, but it doesnt seem to activate UseG1GC. Am I just doing something wrong?

**Comment by pikkon38** [comment] 2016-03-06 15:56
Okay I have also tried putting -XX:+UseConcMarkSweepGC  -XX:-UseConcMarkSweepGC  
-XX:+UseG1GC in the launcher args, and it sufficiently turns off the UseConcMarkSweepGC but still doesnt activate UseG1GC...weird

**Comment by pikkon38** [comment] 2016-03-06 16:20
Update:

Adding this to XML: -XX:-UseConcMarkSweepGC -XX:+CMSIncrementalMode
Adding this to Launcher: -XX:+UseG1GC

Seems to make everything work fine. But I cannot figure out how to take that launcher arg and put it in the xml and make it work

**Comment by RyanTheAllmighty** [comment] 2016-12-29 09:16
Released

**Closed by RyanTheAllmighty** 2016-12-29 09:16 UTC
Labels: Bug, Resolved
