### ISSUE TITLE
x-terminal-emulator not found (servers)

### ISSUE THREAD

**Issue by Redo11** [ATLauncher/ATLauncher#525] opened 2021-11-20 12:38 UTC
**Describe the bug**
Server not starting due to "Cannot run program "x-terminal-emulator" (in directory "**USERSDIR**/servers/Minecraft1171withFabric"): error=2, No such file or directory"

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Vanilla Packs'
2. Click on 'Create Server'
3. Go to 'Servers'
4. Start the server with 'Launch With GUI'
5. See error

**Expected behaviour**

**Logs**
https://pastebin.com/4EtaSG2p

**Screenshots**
![image](https://user-images.githubusercontent.com/49594490/142726378-7b67fee5-2859-45a1-9d2a-e0acba0064e7.png)

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Arch Linux, Garuda Linux
- Java Version: Zulu 11, OpenJDK 17

**Additional context**
Tested on 2 machines

**Comment by RyanTheAllmighty** [comment] 2021-11-20 12:39
Duplicate of #391

**Closed by RyanTheAllmighty** 2021-11-20 12:39 UTC
Labels: bug
