### ISSUE TITLE
System.getenv to System.getProperty and **USERSDIR**

### ISSUE THREAD

**Issue by ghost** [ATLauncher/ATLauncher#264] opened 2016-04-12 18:03 UTC
In my journey to make it work on El Capitan, I get an error about a UnixPath issue.

Tracked it down to this line:
https://github.com/ATLauncher/ATLauncher/blob/3.3.0.0/src/main/java/com/atlauncher/data/OS.java#L98

I changed `System.getenv("user.home")` to `System.getProperty("user.home")`.
http://stackoverflow.com/questions/585534/what-is-the-best-way-to-find-the-users-home-directory-in-java/585558#585558
https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

Guessing this is to make it store the files inside the user data folder on OS X.  However I only see them get downloaded inside the `.app` file, or next to the `.jar` file.  Not inside my "Application Support" folder as I guess the code would facilitate.  `/Users/MindTooth/Application Support/atlauncher`

Does this have something to do with the logs showing `Launcher Directory: **USERSDIR**`, and not a path?

**Comment by RyanTheAllmighty** [comment] 2016-04-12 21:13
Well the intended behaviour is the launcher will download all files within the app itself.

As for the log you're seeing, that's censoring of user data, since we have a log upload feature, we had complaints about exposing that user data publiclly so started censoring it.

If you run with the `--debug` command line argument it will remove censoring, not sure how that works on a Mac.

I have access to a El Capitan machine for work, I'll give it a look on that.

**Comment by RyanTheAllmighty** [comment] 2021-06-12 12:16
Closing this to clean up the issues in the repository.

**Closed by RyanTheAllmighty** 2021-06-12 12:16 UTC
Labels: bug
