### ISSUE TITLE
Search & Sort Box on Edit Mods Page

### ISSUE THREAD

**Issue by ardissaps** [ATLauncher/ATLauncher#630] opened 2022-07-08 00:56 UTC
![image](https://user-images.githubusercontent.com/82106625/177894923-1380b473-0f3f-4795-8b23-b369808820b9.png)
The sorting can be based on last install time and name. 
Thank you, no need to hurry!

**Comment by RyanTheAllmighty** [comment] 2022-07-08 00:59
Duplicate of #556 which is for an overhaul of that entire section. Best to post in there

**Closed by RyanTheAllmighty** 2022-07-08 00:59 UTC
Labels: enhancement

**Comment by ardissaps** [comment] 2022-07-08 01:05
> Duplicate of #556 which is for an overhaul of that entire section. Best to post in there

Sorry! I tried to search but can't find that post, maybe because it is morning and I drink not enough coffee! :D
