### ISSUE TITLE
Popup dialogs can appear behind the main window, locking up the main window

### ISSUE THREAD

**Issue by ScrubN** [ATLauncher/ATLauncher#939] opened 2024-08-17 02:08 UTC
### What happened?

When one dialog closes and another one is opening, it is possible to focus the parent window and thus give it a higher Z-index than the dialog box, completely locking up the application.

Steps to reproduce:
1. Install an instance or update an instance
2. Switch focus to another application
3. At the same instant that the instance is installed/updated, switch focus back to ATLauncher
4. Observe that there is a dialog that is blocking input to the main window, but is behind the main window and thus cannot be dismissed

### Operating System

Windows

### Additional Information

- So far I have experienced this issue naturally twice while updating instances, but I have not been able to successfully reproduce it while screen recording.
- Whichever dialog is causing the lockup seems to completely ignore keyboard inputs such as <kbd>esc</kbd> and <kbd>tab</kbd>+<kbd>space</kbd>, or maybe it ignores the keyboard inputs because it is not properly focused?

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2024-08-17 02:52
Duplicate of #715

**Closed by RyanTheAllmighty** 2024-08-17 02:52 UTC
Labels: bug, triage
