### ISSUE TITLE
ATLauncher windows are hidden until clicked if they become active while ATLauncher isn't focused

### ISSUE THREAD

**Issue by The-Fireplace** [ATLauncher/ATLauncher#428] opened 2021-01-01 18:20 UTC
**Describe the bug**
From time to time, the popup windows from ATLauncher for various actions get hidden behind others until ATLauncher is clicked. This usually seems to happen when focus isn't on ATLauncher for one reason or another and ATLauncher's active window is changed (ex. After adding a mod from CF when that window closes and focus changes back to the CurseForge mods window, video attached)

**To Reproduce**
1. Open ATLauncher
2. Do something that will open or focus on a different ATLauncher window while ATLauncher isn't focused
3. See that the expected window isn't visible
4. Click on ATLauncher and see that the window is actually there and was just hidden by another ATLauncher window

**Expected behavior**
The active ATLauncher window is always on top of the other ATLauncher windows

**Screenshots**
Pay attention to the first half a second or so, this is cropped a little short.
https://user-images.githubusercontent.com/5914284/103444003-2d765800-4c2a-11eb-84b3-a7247be32efd.mp4

**Desktop:**
- OS: MX Linux 19.3
- ATLauncher 3.4.1.1

**Comment by RyanTheAllmighty** [comment] 2021-01-02 00:12
Is this 100% reproducible or random when it happens? If it's random, it may be hard to find and fix the issue.

**Comment by The-Fireplace** [comment] 2021-01-02 00:26
I thought it was random at first, but after I started paying attention to when it was happening and attempting to reproduce the issue in different parts of the application I figured out it's probably because of the focus. Using the steps I followed in the video it is 100% reproducible, I've done it over and over adding different mods from CurseForge with the same results. I will type those steps out in a comment when I get the chance.

**Comment by The-Fireplace** [comment] 2021-01-02 01:22
I take it back, I'm testing it more and it doesn't appear to happen 100% of the time. It is frequent, especially when I switch windows then go back to ATLauncher, but not 100%. I'm aware that makes it harder to reproduce and fix so I'll keep an eye out for any other similarities about when it happens and let you know if I see any.

**Comment by RyanTheAllmighty** [comment] 2021-01-04 08:52
Okay so I found the issue. Looks like when we open certain dialog windows (such as Add Mod) we were telling it that the main ATLauncher window is the parent, not the actual parent (in the example the Edit Mods dialog), so it was showing the dialog under that dialog.

Windows doesn't care about this and will show the dialog correctly, but seems on some desktop environments for linux and OSX it will not show it until the window is clicked.

So this can be fixed. I'll look around for places doing this and fix it up where possible.

**Comment by RyanTheAllmighty** [comment] 2021-01-09 02:41
Released with version 3.4.2.0

**Closed by RyanTheAllmighty** 2021-01-09 02:41 UTC
Labels: bug
