### ISSUE TITLE
Add option for less strict Add Mod restrictions

### ISSUE THREAD

**Issue by zauberparacelsus** [ATLauncher/ATLauncher#439] opened 2021-01-25 13:09 UTC
**Is your feature request related to a problem? Please describe.**
When installing curseforge mods from within the launcher, the "Disable Add Mod Restrictions" is all or nothing, requiring that the user take extra care to install mods for the wrong minecraft version or the wrong mod loader

**Describe the solution you'd like**
What I propose is an option called "Less Strict Add Mod Restrictions", which would serve as a halfway point between the all-or-nothing approach above.  Instead of checking for an exact minecraft version match, it would only check the major version.  So if you're running Minecraft 1.16.5, it would show mods for any 1.16.x version.  This would be useful, as several mods compiled for one version of minecraft will still work in other minor versions within the same major version.

**Describe alternatives you've considered**
Manually downloading and installing mods which don't show up in the Add Mod browser.

**Additional context**
None to provide.

**Comment by RyanTheAllmighty** [comment] 2021-01-25 18:20
The problem is the curseforge API doesn't support this.

You have to filter on a single version, or nothing, so while it could be done at a project level, so you can only install files for the same major version of Minecraft, it would lead to mods showing up in the search that you wouldn't be able to install.

Not sure if it's still useful or not, but given Modrinth support filtering on multiple versions, would make sense to have this, even if the functionality is gimped when using curseforge

**Comment by zauberparacelsus** [comment] 2021-01-27 12:50
Ah, I see.  Best idea I have is perhaps filtering the returned results on the client-side.  But that would depend on how much information the curseforge API is exposing in the returned results.

**Comment by RyanTheAllmighty** [comment] 2021-01-27 12:52
Yeah it just does it on the client side, so you may see mods in the list, but then have no files when trying to install. But again it's probably a better trade off.

**Comment by RyanTheAllmighty** [comment] 2021-02-02 11:50
Released with version 3.4.3.0

**Closed by RyanTheAllmighty** 2021-02-02 11:50 UTC
Labels: awaiting-release, enhancement
