### ISSUE TITLE
Buttons Open / Open folder not working 

### ISSUE THREAD

**Issue by mmariposa** [ATLauncher/ATLauncher#928] opened 2024-07-22 00:18 UTC
### What happened?

This happens on Arch Linux. ATLauncher installed via flathub.

1. Open Launcher
2. Go to instances tab and press the 'Open folder' button in any instance

This also happens in the prompt for downloading mods manually.

Please let me know if I can provide any more info

### Operating System

Linux

### Relevant log output

```shell
[22/07/2024 02:08:47 a. m.] Error opening file explorer!
[22/07/2024 02:08:47 a. m.] java.io.IOException: Failed to show URI:file:**USERSDIR**/instances/BahadeVapor/
[22/07/2024 02:08:47 a. m.] 	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:87)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Desktop.open(Desktop.java:431)
[22/07/2024 02:08:47 a. m.] 	at com.atlauncher.utils.OS.openFileExplorer(OS.java:207)
[22/07/2024 02:08:47 a. m.] 	at com.atlauncher.utils.OS.openFileExplorer(OS.java:189)
[22/07/2024 02:08:47 a. m.] 	at com.atlauncher.gui.card.InstanceCard$1.mousePressed(InstanceCard.java:87)
[22/07/2024 02:08:47 a. m.] 	at com.atlauncher.gui.components.DropDownButton$1.mousePressed(DropDownButton.java:55)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[22/07/2024 02:08:47 a. m.] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[22/07/2024 02:08:47 a. m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[22/07/2024 02:08:47 a. m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[22/07/2024 02:08:47 a. m.] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[22/07/2024 02:08:47 a. m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[22/07/2024 02:08:47 a. m.] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[22/07/2024 02:08:47 a. m.] java.io.IOException: Failed to show URI:file:**USERSDIR**/instances/BahadeVapor/
	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
	at java.desktop/sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:87)
	at java.desktop/java.awt.Desktop.open(Desktop.java:431)
	at com.atlauncher.utils.OS.openFileExplorer(OS.java:207)
	at com.atlauncher.utils.OS.openFileExplorer(OS.java:189)
	at com.atlauncher.gui.card.InstanceCard$1.mousePressed(InstanceCard.java:87)
	at com.atlauncher.gui.components.DropDownButton$1.mousePressed(DropDownButton.java:55)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2024-07-22 00:21
Duplicate of #713 713

**Closed by RyanTheAllmighty** 2024-07-22 00:21 UTC
Labels: bug, triage
