### ISSUE TITLE
Add support for packaging the macOS universal to support Apple silicon (a solution suggestion)

### ISSUE THREAD

**Issue by ellet0** [ATLauncher/ATLauncher#900] opened 2024-05-16 09:37 UTC
### The Problem

Right now, the plugin [macos-app-bundle](https://github.com/crotwell/gradle-macappbundle) is no longer maintained and the author [suggested](https://github.com/crotwell/gradle-macappbundle/issues/73#issuecomment-756858348) to use other alternatives

and still, we have to use different plugins and solutions which will cause a lot of duplicated code that requires more maintenance, a solution that has all in one plugin would be very useful 

Related issues:

- #502 
- #559

### The Solution

 I can suggest a few alternatives that will is designed for packaging the application for other OS (all in one gradle plugin):

- https://conveyor.hydraulic.dev/14.2/comparisons/jvm-comparisons/
- https://docs.oracle.com/en/java/javase/21/docs/specs/man/jpackage.html
- https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Native_distributions_and_local_execution (for compose desktop but the Gradle plugin of it can be used for other type of applications like Java Swing)

jpackage and Compose desktop have one downside which require to use Java 17 JDK, but only for the Gradle (only in development), the final application will still need Java 8 as a requirement

Also the configurations seems to be a lot easier (all from one place and universal, instead of different plugins and configurations):

```

application {
        nativeDistributions {
            packageName = "ExampleApp"
            packageVersion = "0.1-SNAPSHOT"
            description = "Example App"
            copyright = "© 2020 My Name. All rights reserved."
            vendor = "Example vendor"
            licenseFile.set(project.file("LICENSE.txt"))
            macOS {
                // macOS specific options
            }
            windows {
                // Windows specific options
            }
            linux {
                // Linux specific options
            }
        }
    }

```

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2024-05-16 09:45
Duplicate of #559

**Closed by RyanTheAllmighty** 2024-05-16 09:45 UTC
Labels: enhancement, triage
