### ISSUE TITLE
ATL will get stuck under certain circumstances

### ISSUE THREAD

**Issue by zeng-github01** [ATLauncher/ATLauncher#887] opened 2024-04-21 16:18 UTC
### What happened?

1.Open ATL
2.Install an instance such as Modpack
3.When the prompt for manual download of Mods appears, jump to Edge/Chrome etc to download.
4.After ATL displays that the installation is complete, click outside the ATL interface, such as a certain point in the browser, or the desktop (I don’t remember clearly)
5.The ATL prompt after the installation is completed will disappear. At the same time, you cannot click anywhere in ATL. Every time you click, the Windows prompt sound will appear (maybe just the sound of invalid operation).

6.Finally I was forced to use Task Manager to force close ATL.

### Operating System

Windows

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2024-04-21 21:59
Duplicate of #715

**Closed by RyanTheAllmighty** 2024-04-21 21:59 UTC
Labels: duplicate
