### ISSUE TITLE
Add the "Add Mods" and "Edit Mods" features to Servers too

### ISSUE THREAD

**Issue by JumperCzech** [ATLauncher/ATLauncher#534] opened 2021-12-08 10:39 UTC
these lil convenient things
![image](https://user-images.githubusercontent.com/83337894/145194251-7fd1beba-47e7-468e-970f-ebf2443f127b.png)

**Comment by RyanTheAllmighty** [comment] 2021-12-08 10:48
Duplicate of #421

**Closed by RyanTheAllmighty** 2021-12-08 10:48 UTC
Labels: enhancement
