### ISSUE TITLE
Hang/Error after updating mods

### ISSUE THREAD

**Issue by ashwga** [ATLauncher/ATLauncher#699] opened 2023-01-05 11:26 UTC
**Describe the bug**
After updating mods in the edit mods menu hangs because of "Window must not be zero" => unable to update any mods via launcher

**To Reproduce**
1. Click edit mods on an instance (1.19.2 with fabric in my case) 
2. Select any mod
3. Click "Check for updates"
4. Add any available updates
5. Right after it finishes it hangs on "Checking for updates"

**Logs**
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalArgumentException: Window must not be zero
	at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:56)
	at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:73)
	at java.desktop/sun.awt.X11.XlibUtil.isToplevelWindow(XlibUtil.java:312)
	at java.desktop/sun.awt.X11.XWindowPeer.setToplevelTransientFor(XWindowPeer.java:1676)
	at java.desktop/sun.awt.X11.XWindowPeer.restoreTransientFor(XWindowPeer.java:1852)
	at java.desktop/sun.awt.X11.XWindowPeer.removeFromTransientFors(XWindowPeer.java:1916)
	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1630)
	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1602)
	at java.desktop/java.awt.Window.setModalBlocked(Window.java:1535)
	at java.desktop/java.awt.Dialog.unblockWindow(Dialog.java:1569)
	at java.desktop/java.awt.Window.updateChildrenBlocking(Window.java:1763)
	at java.desktop/java.awt.Dialog.modalShow(Dialog.java:1437)
	at java.desktop/java.awt.Dialog.modalHide(Dialog.java:1463)
	at java.desktop/java.awt.Dialog.hideAndDisposePreHandler(Dialog.java:1130)
	at java.desktop/java.awt.Dialog.hide(Dialog.java:1159)
	at java.desktop/java.awt.Component.show(Component.java:1730)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at com.atlauncher.gui.dialogs.ProgressDialog.close(ProgressDialog.java:157)
	at com.atlauncher.gui.dialogs.EditModsDialog.lambda$checkForUpdates$19(EditModsDialog.java:403)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Screenshots**
![image](https://user-images.githubusercontent.com/57142641/210768985-41e27fbc-cf06-40e3-8e66-62113a388574.png)

**System information (please complete the following information, or remove if not applicable):**
- OS: Arch Linux with linux 6.1.1
- Java Version: openjdk version "19.0.1" 2022-10-18

**Comment by RyanTheAllmighty** [comment] 2023-10-29 23:23
Duplicate of #772, even though this one is earlier, that one has a bit more info, will merge

**Closed by RyanTheAllmighty** 2023-10-29 23:23 UTC
Labels: bug, low-priority
