### ISSUE TITLE
Curseforge: Invalid file reference in manifest

### ISSUE THREAD

**Issue by CorneliusCornbread** [ATLauncher/ATLauncher#875] opened 2024-02-22 23:31 UTC
### What happened?

For some reason, maybe due to a mod being present on both CF and modrinth, when exporting a pack to curseforge it will contain duplicate references to mods in its manifest. This causes curseforge to get really upset when uploading a modpack and reject the pack.

For example
```
Invalid file reference in manifest: File ID 4725669 () appears more than once.
```

### Operating System

Linux

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment] 2024-02-22 23:55
Can you please share 2 things, the `instance.json` for the instance, and the export zip file you're using to upload the CurseForge that's being rejected.

If this is a private pack you don't want to share publicly, please feel free to DM me on [Discord](https://atl.pw/discord).

**Comment by CorneliusCornbread** [comment] 2024-02-23 01:15
> Can you please share 2 things, the `instance.json` for the instance, and the export zip file you're using to upload to CurseForge that's being rejected.
> 
> If this is a private pack you don't want to share publicly, please feel free to DM me on [Discord](https://atl.pw/discord).

The file is unfortunately a bit too big for GH, it's uhh... quite a big pack with mods spread over both curseforge and modrinth. I'll send it over Discord, it's eventually going to be a public pack but for now I can't upload it :P

Here's the instance json
[instance.json](https://github.com/ATLauncher/ATLauncher/files/14380779/instance.json)

**Comment by RyanTheAllmighty** [comment] 2024-02-23 01:24
> > Can you please share 2 things, the `instance.json` for the instance, and the export zip file you're using to upload to CurseForge that's being rejected.
> > If this is a private pack you don't want to share publicly, please feel free to DM me on [Discord](https://atl.pw/discord).
> 
> The file is unfortunately a bit too big for GH, it's uhh... quite a big pack with mods spread over both curseforge and modrinth. I'll send it over Discord, it's eventually going to be a public pack but for now I can't upload it :P
> 
> Here's the instance json [instance.json](https://github.com/ATLauncher/ATLauncher/files/14380779/instance.json)

Just the manifest.json that's inside the CurseForge zip should be enough

**Comment by CorneliusCornbread** [comment] 2024-02-23 03:07
> > > Can you please share 2 things, the `instance.json` for the instance, and the export zip file you're using to upload to CurseForge that's being rejected.
> > > If this is a private pack you don't want to share publicly, please feel free to DM me on [Discord](https://atl.pw/discord).
> > 
> > 
> > The file is unfortunately a bit too big for GH, it's uhh... quite a big pack with mods spread over both curseforge and modrinth. I'll send it over Discord, it's eventually going to be a public pack but for now I can't upload it :P
> > Here's the instance json [instance.json](https://github.com/ATLauncher/ATLauncher/files/14380779/instance.json)
> 
> Just the manifest.json that's inside the CurseForge zip should be enough

Happy to oblige, this should be much easier to download then
[manifest.json](https://github.com/ATLauncher/ATLauncher/files/14381271/manifest.json)

**Comment by RyanTheAllmighty** [comment] 2024-02-23 03:39
Okay the issue is with `Backpacked` mod. It's in the `instance.json` twice which is odd.

But the export process just takes all mods in the json, makes sure it exists in the file system, then puts it in the `manifest.json`.

So it's not checking for duplicates, which it should be.

So there's 2 issues here to fix:

- `instance.json` should never allow mods to be in there twice
- When exporting to CurseForge (Modrinth probably also has this issue), don't duplicate file ids (maybe also warn if there's duplicate mod ids)

Will take a look and fix up this weekend

**Comment by CorneliusCornbread** [comment] 2024-02-26 13:50
Unfortunately this seems to still be persisting, just without duplicate mods

```
Invalid manifest.json file:
References invalid fileIDs: fileID: 4632444, projectID 871698 (project-871698).
References file with invalid status: 4998424 (projectID 925913 - Rejected). 
```

**Comment by CorneliusCornbread** [comment] 2024-02-26 13:58
Updated manifest
[manifest.json](https://github.com/ATLauncher/ATLauncher/files/14405644/manifest.json)

**Comment by CorneliusCornbread** [comment] 2024-02-26 14:11
I wonder if it has something to do with the fact that my preferred mod platform is modrinth? If for some reason that's making things behave oddly?

**Comment by CorneliusCornbread** [comment] 2024-02-27 20:59
@RyanTheAllmighty Should I open another issue for this?

**Comment by RyanTheAllmighty** [comment] 2024-02-27 22:08
So lookign at it:

> References invalid fileIDs: fileID: 4632444, projectID 871698 (project-871698).
This is pointing to `create-structures-0.1.1-1.20.1-FORGE.jar` which is marked as no longer available in CurseForge's api, and the project itself looks like it's been removed from CurseForge entirely.

My understanding is CurseForge should still allow deleted projects to appear in modpacks, so they don't break. It might be only for existing packs and they reject all new submissions.

I think currently we don't handle anything to do with deleted mods in the CurseForge api, because if they get deleted after the time that you've added them into the instance, we won't know they've been removed, so we can simply not export mods that have been deleted and add them to the overrides, but we'd now need to start scanning every mod you have on export.

Alternatively we don't do that, and fallback to getting users to rescan the metadata in the edit mods page for those mods.

> References file with invalid status: 4998424 (projectID 925913 - Rejected). 
Similar issue as above, but this time the file itself is deleted, not the project. Looks like they deleted the file you now reference from https://www.curseforge.com/minecraft/mc-mods/create-interactive

They have this message on their CurseForge page:

> All new releases are on our website / Modrinth, please download them there:

So looks like they've moved to Modrinth

Pretty much same solution as above, just check if the files available before exporting it in the zip

I'll reopen this and get it fixed up tonight

**Closed** 2024-02-28 11:32 UTC
Labels: bug, high-priority
