### ISSUE TITLE
zip-file modpack import fails- version begins with null

### ISSUE THREAD

**Issue by akii0008** [ATLauncher/ATLauncher#467] opened 2021-04-24 19:17 UTC
**Describe the bug**
Hello! Looks like the importing process is a bit borked; all is fine with selecting the actual zip file, but when I hit the "Import" button at the final stage, it throws a NullPointerException error in my log file (see [this massive error stack](https://pastebin.com/m5KhRLZc))

**To Reproduce**

0. You'll have to run the ATLauncher jar file- I haven't found a way to view the error otherwise
1. Grab a curseforge(?) pack as a zip file
2. Import it, as in press the import button and follow thru the steps to the end lol
3. Actually press the Install button on the final step
4. Check out the logs

**Expected behavior**
It imports and the pack is playable

**Logs**
[This pastebin stack trace](https://pastebin.com/m5KhRLZc)

**Screenshots**
![image](https://user-images.githubusercontent.com/26691026/115970293-73279b00-a50f-11eb-80b1-a46c66ef82e6.png)

You'll see that the version dropdown begins with null.. I don't think that's supposed to be there?

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): KDE Neon 5.21.4 (built on Ubuntu 20.04)
- Java Version: OpenJDK Java 11.0.10

**Comment by akii0008** [comment] 2021-04-24 19:33
I figure i should also attach the zip file i used just in case there's something wrong with it and not the import function: [CoolCraft.zip](https://github.com/ATLauncher/ATLauncher/files/6370466/CoolCraft.zip)

**Comment by RyanTheAllmighty** [comment] 2021-04-24 22:25
Where did you get this zip from? It's trying to get the version number from CurseForge but the manifest doesn't have a project id in it so it breaks. It shouldn't break, but that's the cause. Guessing this isn't on CurseForge and was just exported direct from their client?

**Comment by RyanTheAllmighty** [comment] 2021-04-25 06:04
Fixed and released with version 3.4.3.2

**Closed by RyanTheAllmighty** 2021-04-25 06:04 UTC
Labels: awaiting-release, bug

**Comment by akii0008** [comment] 2021-04-25 15:24
Awesome, thank you very much! And yes this isn't on CurseForge, it was exported from my friend's client which is why it doesn't have a version. I should have included that
