### ISSUE TITLE
Total GUI freeze when log messages come in fast.

### ISSUE THREAD

**Issue by MaPePeR** [ATLauncher/ATLauncher#138] opened 2015-02-14 17:17 UTC
This should not happen. Never block the main GUI thread. there is no good reason for it.

**Comment by s0cks** [comment] 2015-02-14 17:21
We are not purposefully blocking the main thread it happens to come from the logging thread. When the logging threads blocking queue reaches its maximum capacity it locks the thread that tried to insert until it can insert there is no way around it and I'm not writing a synchronous logger when the asynchronous one works quite well

**Comment by s0cks** [comment] 2015-02-14 17:22
A synchronous logger would be worse

**Comment by MaPePeR** [comment] 2015-02-14 17:32
This could be interesting to solve this issue: http://javatechniques.com/blog/faster-jtextpane-text-insertion-part-ii/

**Comment by s0cks** [comment] 2015-02-14 17:34
That wouldn't solve the problem

**Comment by MaPePeR** [comment] 2015-02-14 17:44
My assumption on what is locking the main gui thread: The Updates into the logger come in so fast, that it constantly calls the `Document.insertString`-Method, which is thread safe. So the logger constantly locks the Document from being used by other Threads. This causes the main GUI thread to be locked because the Logger is faster at acquiring the lock for the Document.
Batch-Inserting multiple log entrys at once when they are present would result in less locking being done.

**Comment by s0cks** [comment] 2015-02-14 17:44
did you not read my comment? Ill post it again for you:

We are not purposefully blocking the main thread it happens to come from the logging thread. When the logging threads blocking queue reaches its maximum capacity it locks the thread that tried to insert until it can insert there is no way around it and I'm not writing a synchronous logger when the asynchronous one works quite well

**Comment by MaPePeR** [comment] 2015-02-14 17:56
I never said, that you are *purposefully* blocking the main thread.
But you **do** block it, and even if its not on purpose its still a bug that exists in your code. 
I made an assumption on what is *unpurposefully* blocking the main gui thread and ask you to consider taking another look at it. 
Even if a bug is not purposefully introduced into a program its still worth fixing. I never said, that you need to write a totally new async or sync logger or anything. 

Also i'm not sure that you actually read the link at all. [Part I](http://javatechniques.com/blog/faster-jtextpane-text-insertion-part-i/) might also be interesting, because it shows that calling the `insertString`-Method repeatedly can be very slow. (And this is done in the code)
And if that `insertString`-Method call is slow it will result in the blocking queue filling up...

I think that's at least an assumption for what is causing that issue that is better than your "it happens to come from the logging thread"

>When the logging threads blocking queue reaches its maximum capacity it locks the thread that tried to insert until it can insert
But the logging thread is not the main gui thread, so that is not an explanation for the main gui thread being locked.

**Comment by s0cks** [comment] 2015-02-14 17:59
yes there is an explanation for the main swing thread being blocked, if you understood concurrency in java you would know that when a blocking queue is full and inserted the thread that is doing the insertion gets blocked till it can insert in order to nullify potential memory leaks

**Comment by MaPePeR** [comment] 2015-02-14 17:59
Yes i understand that.

But what thread is doing the insertion again? 
NOT the main gui thread.

**Comment by s0cks** [comment] 2015-02-14 18:00
the main GUI thread is doing the insertion, so is the main java thread

**Comment by MaPePeR** [comment] 2015-02-14 18:01
so if the main GUI thread does the insertion: there is your bug. it should not do that.
(And from looking at the code it does not do that. This is done by an anonymous thread implementation in `Instance`)

**Comment by s0cks** [comment] 2015-02-14 18:02
its not a bug in the code, in order for the logging to happen with as much limited resources as possible it needs to insert from exactly where it got it.

**Comment by MaPePeR** [comment] 2015-02-14 18:04
but as i just pointed out the insertion is not done from the main GUI thread. (That would be even more horrible, because it would mean, that the whole ATLauncher would be frozen until you close minecraft)

**Comment by s0cks** [comment] 2015-02-14 18:06
Im closing this to spare arguments its not a bug nor is there anything wrong I will increase the size of the blocking queue AGAIN, thats all that needs to be done

**Comment by MaPePeR** [comment] 2015-02-14 18:07
are you even reading what i'm writing?

**Closed by s0cks** 2015-02-14 18:06 UTC

**Comment by s0cks** [comment] 2015-02-14 18:08
yes I am

**Comment by s0cks** [comment] 2015-02-14 18:10
I locked the issue to spare argument, Ryan if you want to unlock it because you think theres a real "issue" fine by me, but I know what is going on and theres no fixing it besides implementing a new logger that doesnt use a blocking queue and is asynchronous (note that it is impossible)

**Comment by RyanTheAllmighty** [comment] 2015-02-14 18:17
I trust s0cks knows what she's doing. If you want to provide a pull request I'm happy to look at it, otherwise I trust s0cks in what she says.
